// US metro areas with large Ukrainian communities. Each one costs one SerpApi search per run,
// so a weekly run of all of them uses ~80 of the free plan's 250 searches/month.
export const cities = [
    "New York, NY",
    "Chicago, IL",
    "Philadelphia, PA",
    "Washington, DC",
    "Los Angeles, CA",
    "San Francisco, CA",
    "Sacramento, CA",
    "Seattle, WA",
    "Portland, OR",
    "Detroit, MI",
    "Cleveland, OH",
    "Pittsburgh, PA",
    "Boston, MA",
    "Newark, NJ",
    "Baltimore, MD",
    "Minneapolis, MN",
    "Denver, CO",
    "Houston, TX",
    "Atlanta, GA",
    "Miami, FL",
];
